;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.State.Dead",DevComment="")
+GameplayTagList=(Tag="Character.State.HasArmor",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Health",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Shield",DevComment="")
+GameplayTagList=(Tag="Data.Guns.Ammo",DevComment="")
+GameplayTagList=(Tag="Data.Guns.MaxAmmo",DevComment="")

