;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="SetByCaller.Cooldown.SixShooter.Fire",NewTagName="SetByCaller.SixShooter.Cooldown.Fire")
+GameplayTagRedirects=(OldTagName="Data.LastBullet",NewTagName="Data.IsLastBullet")
+GameplayTagRedirects=(OldTagName="Data.Precision",NewTagName="Data.IsPrecision")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Cooldown.Fire",NewTagName="SetByCaller.SixShooter.Cooldown.Shoot")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Damage.Fire",NewTagName="SetByCaller.SixShooter.Damage.Shoot")
+GameplayTagRedirects=(OldTagName="GameplayCue.SixShooter.Fire",NewTagName="GameplayCue.SixShooter.Shoot")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Cooldown.Shoot",NewTagName="SetByCaller.Creek.Cooldown.Shoot")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Cooldown",NewTagName="SetByCaller.Creek.Cooldown")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Damage.Shoot",NewTagName="SetByCaller.Creek.Damage.Shoot")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter.Damage",NewTagName="SetByCaller.Creek.Damage")
+GameplayTagRedirects=(OldTagName="SetByCaller.SixShooter",NewTagName="SetByCaller.Creek")
+GameplayTagList=(Tag="Character.Buffs.Invulnerable",DevComment="")
+GameplayTagList=(Tag="Character.Debuffs.Slow",DevComment="")
+GameplayTagList=(Tag="Character.State.Dead",DevComment="")
+GameplayTagList=(Tag="Character.State.Stunned",DevComment="")
+GameplayTagList=(Tag="Cooldown.Firefly",DevComment="")
+GameplayTagList=(Tag="Cooldown.SixShooter.Fire",DevComment="")
+GameplayTagList=(Tag="Data.IsLastBullet",DevComment="")
+GameplayTagList=(Tag="Data.IsPrecision",DevComment="")
+GameplayTagList=(Tag="Data.Payload",DevComment="")
+GameplayTagList=(Tag="Enchantment.Trigger.OnHit",DevComment="")
+GameplayTagList=(Tag="Enchantment.Trigger.OnKill",DevComment="")
+GameplayTagList=(Tag="Enchantment.Trigger.OnPrecisionHit",DevComment="")
+GameplayTagList=(Tag="Enchantment.Trigger.OnPrecisionKill",DevComment="")
+GameplayTagList=(Tag="Enchantment.Trigger.OnShot",DevComment="")
+GameplayTagList=(Tag="Enchantment.Weapon.Firefly",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Firefly",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SixShooter.Shoot",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Cooldown",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Damage",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Duration",DevComment="")
+GameplayTagList=(Tag="SetByCaller.PrecisionHits",DevComment="")

